studentsdb/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

# from students.views.testview import StudentList
# from students.views.contact_admin_class import ContactAdmin

# Domashka 343
# from students.views.contact import KontaktView

# Domashka 352
# from students.views.kontakt_admin_class import KontaktAdmin

# str361
from students.views.students import StudentUpdateView, StudentDeleteView, StudentAddView

# Domashka 365 GroupDeleteView
from students.views.groups import GroupAddView, GroupEditView, GroupDeleteView, groups_list

from students.views.journal import JournalView

from students.views.exams import ExamAddView, ExamEditView, ExamDeleteView, exams_list

from students.views.logentries import log_list

from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.views.generic.base import RedirectView, TemplateView
from django.contrib.auth.decorators import permission_required

js_info_dict = {
    'packages': ('students'),
}

urlpatterns = patterns('',

         # Javascript translation
         url(r'^jsi18n\.js$',
             'django.views.i18n.javascript_catalog', js_info_dict),

         # i18n
         url(r'^i18n/', include('django.conf.urls.i18n')),

         # Students urls
         url(r'^$', 'students.views.students.students_list', name='home'),

         # domashka 361
         url(r'^students/add/$', StudentAddView.as_view(),
             name='students_add'),

         url(r'^students/(?P<pk>\d+)/edit/$',
             StudentUpdateView.as_view(),
             name='students_edit'),

         url(r'^students/(?P<pk>\d+)/delete/$',
             StudentDeleteView.as_view(),
             name='students_delete'),


         # Groups Listing urls

         url(r'^groups/$', login_required(groups_list), name='groups'),

         url(r'^groups/add/$', login_required(GroupAddView.as_view()),
             name='groups_add'),

         url(r'^groups/(?P<pk>\d+)/edit/$', login_required(GroupEditView.as_view()),
             name='groups_edit'),

         url(r'^groups/(?P<pk>\d+)/delete/$',
             login_required(GroupDeleteView.as_view()),
             name='groups_delete'),

         # Journal urls

         url(r'^journal/(?P<pk>\d+)?/?$',
             login_required(JournalView.as_view()), name='journal'),


         # Exams Listing urls
         url(r'^exams/$', login_required(exams_list), name='exams'),


         url(r'^exams/add/$', login_required(ExamAddView.as_view()),
             name='exams_add'),

         url(r'^exams/(?P<pk>\d+)/edit/$', login_required(ExamEditView.as_view()),
             name='exams_edit'),

         url(r'^exams/(?P<pk>\d+)/delete/$', login_required(ExamDeleteView.as_view()),
             name='exams_delete'),


         # Contact Admin Form
         url(r'^contact-admin/$', 'students.views.contact_admin.contact_admin',
             name='contact_admin'),

         url(r'^log/$', permission_required('auth.add_user')(log_list),
             name='log'),

         # User Related urls


         url(r'^users/logout/$', auth_views.logout, kwargs={'next_page': 'home'},
             name='auth_logout'),

         url(r'^register/complete/$', RedirectView.as_view(pattern_name='home'),
             name='registration_complete'),
         #
         url(r'^users/profile/$', login_required(TemplateView.as_view(
             template_name='registration/profile.html')), name='profile'),

         url(r'^accounts/profile/$', login_required(TemplateView.as_view(
             template_name='registration/profile.html')), name='profile'),


         url(r'^users/', include('registration.backends.simple.urls',
                                 namespace='users')),

         url('^social/', include('social.apps.django_app.urls',
                                 namespace='social')),
         # Default admin url
         url(r'^admin/', include(admin.site.urls)),

         )

from .settings import MEDIA_ROOT, DEBUG

if DEBUG:
    # serve files from media folder
    urlpatterns += patterns('',
                            url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                                'document_root': MEDIA_ROOT}))

students/models.py
# -*- coding: utf-8 -*-

from django.db import models

# Create your models here.
class Student(models.Model):
    """Student Model"""

    class Meta(object):
        verbose_name=u"Студент"
        verbose_name_plural=u"Студенты"

    first_name = models.CharField(
        max_length = 256,
        blank = False,
        verbose_name= u"Имя")

    last_name = models.CharField(
        max_length=256,
        blank=False,
        verbose_name=u"Фамилия")

    middle_name = models.CharField(
        max_length=256,
        blank=True,
        verbose_name=u"Отчество",
        default = '')

    birthday = models.DateField(
        blank=False,
        verbose_name=u"Дата рождения",
        null = True)

    photo = models.ImageField(
        blank=True,
        verbose_name=u"Фото",
        null=True)

    ticket = models.CharField(
        max_length=256,
        blank=False,
        verbose_name = u"Билет")

    notes = models.TextField(
        blank=True,
        verbose_name=u"Дополнительные заметки")

    # number = models.CharField(
    #     max_length = 6,
    #     )

    def __unicode__(self):
        return u"%s %s" % (self.first_name,self.last_name)
    # def __unicode__(self):
    #     return u"%s %s" % (unicode(self.first_name),unicode(self.last_name))

    student_group = models.ForeignKey('Group',
        verbose_name=u"Група",
        blank=False,
        null=True,
        on_delete=models.PROTECT)

class Group(models.Model):
    """Group Model"""


    class Meta(object):
        verbose_name=u"Група"
        verbose_name_plural=u"Групи"

    title = models.CharField(
        max_length = 256,
        blank = False,
        verbose_name= u"Назва")


    starosta = models.OneToOneField('Student',
        verbose_name=u"Староста",
        blank=True,
        null = True,
        on_delete = models.SET_NULL,
        )


    notes = models.TextField(
        blank=True,
        verbose_name=u"Дополнительные заметки")

    def __unicode__(self):
        if self.starosta:
            return u"%s (%s %s)" % (self.title,self.starosta.first_name,self.starosta.last_name)
        else:
            return u"%s" % (self.title,)

    #     if self.starosta:
    #         return u"%s (%s %s)" % (unicode(self.title),unicode(self.starosta.first_name),unicode(self.starosta.last_name))
    #     else:
    #         return u"%s" % (unicode(self.title),)

students/forms.py
# studentsdb
# students/forms.py

from django.forms import (
    Form,
    ModelChoiceField,
)

from students.models.group import Group


class ChangeGroupForm(Form):
    """
    Form for admin action 'change group'
    """

    group = ModelChoiceField(queryset=Group.objects.all().order_by('title'),
                             required=False)

students/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
# Create your views here.
from django.http import HttpResponse

# Views for students
def students_list(request):
    # return HttpResponse('<h1>Hello World</h1>') 
    # return render(request, 'students/students_list.html',{})
    students = (
        {'id':1,
        'first_name':u'Андрей',
        'last_name':u'Корост',
        'ticket':235,
        'image': 'img/me.jpeg'},
        {'id':2,
        'first_name':u'Светлана',
        'last_name':u'Ильдирова',
        'ticket':2358,
        'image': 'img/piv.png'},
        {'id':3,
        'first_name':u'Василий',
        'last_name':u'Пупкин',
        'ticket':2935,
        'image': 'img/podoba3.jpg'},
    )
    return render(request, 'students/students_list.html',
        {'students': students})

# def students_edit(request):
#   return HttpResponse('<h1>Student Add Form232</h1>') 

def students_add(request):
    return HttpResponse('<h1>Student Add Form</h1>') 

def students_edit(request,sid):
    return HttpResponse('<h1>Edit Student %s</h1>' % sid)

def students_delete(request,sid):
    return HttpResponse('<h1>Delete Student %s</h1>' % sid)

# Views for Groups
def groups_list(request):
    # return HttpResponse('<h1>Groups Listing</h1>')
    groups = (
        {'id':1,
        'nazva':u'Мтм-21',
        'starosta': 'Ячменев Олег'},
        {'id':2,
        'nazva':u'Мтм-22',
        'starosta': 'Виталий Подоба'},
        {'id':3,
        'nazva':u'Мтм-23',
        'starosta': 'Иванов Андрей'},
    )
    return render(request, 'students/groups_list.html',
        {'groups': groups})
    
# groups
def groups_add(request):
    return HttpResponse('<h1>Group Add Form</h1>')

def groups_edit(request,gid):
    return HttpResponse('<h1>Edit Group %s</h1>' % gid)

def groups_delete(request,gid):
    return HttpResponse('<h1>Delete Group %s</h1>' % gid)

students/views/contact_admin.py
import logging

from django.shortcuts import render
from django import forms

from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

from studentsdb.settings import ADMIN_EMAIL

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from django.contrib import messages

from django.dispatch import Signal
from django.contrib.auth.decorators import permission_required
from django.utils.translation import ugettext as _


class ContactForm(forms.Form):

    def __init__(self, *args, **kwargs):
        # call original initializator
        super(ContactForm, self).__init__(*args, **kwargs)

        # this helper object allows us to customize form
        self.helper = FormHelper()

        # form tag attributes
        self.helper.form_class = 'form-horizontal col-xs-10'
        self.helper.form_method = 'post'
        self.helper.form_action = reverse('contact_admin')

        # twitter bootstrap styles
        self.helper.help_text_inline = True
        self.helper.html5_required = True
        self.helper.label_class = 'col-sm-2 control-label'
        self.helper.field_class = 'col-sm-10'

        # form buttons
        self.helper.add_input(Submit('send_button', _(u'Send')))

    from_email = forms.EmailField(
        label=_(u'Your email'))

    subject = forms.CharField(
        label=_(u'Subject'),
        max_length=128)

    message = forms.CharField(
        label=_(u'Message for admin'),
        max_length=2560,
        widget=forms.Textarea)

# Signal after sending mail to admin 526
# Create signal.
email_was_send = Signal(providing_args=['subject', 'email'])

email_was_send.connect(simple_receiver)


def send_signal_email_for_admin(subject, email):
    email_was_send.send(sender='send_signal_email_for_admin',
                        subject=subject, email=email)


@permission_required('auth.add_user')
def contact_admin(request):
    # check if form was posted
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = ContactForm(request.POST)

        # check whether user data is valid:
        if form.is_valid():  # send email
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            from_email = form.cleaned_data['from_email']

            try:
                send_mail(subject, message, from_email, [ADMIN_EMAIL])
            except Exception:
                messages.error(request, _(u"When sending a letter, an unexpected error occurred.\
                 Try to use this form later."))
                logger = logging.getLogger(__name__)
                logger.exception('message')
            else:
                send_signal_email_for_admin(subject, from_email)
                mail_logger = logging.getLogger('email_was_send')
                mail_logger.info(
                    "Email from %s was send with next subject: %s", from_email, subject)
                messages.success(request, _(
                    u'The message was successfully sent'))

            # redirect to same contact page with success message
            return HttpResponseRedirect(reverse('contact_admin'))

    # if there was not POST render blank form
    else:
        form = ContactForm()

    return render(request, 'contact_admin/form.html', {'form': form})

students/views/journal.py
from datetime import datetime, date
from dateutil.relativedelta import relativedelta
from calendar import monthrange, weekday, day_abbr

from django.http import JsonResponse
from django.core.urlresolvers import reverse
from django.views.generic.base import TemplateView

from ..models.student import Student
from ..models.monthjournal import MonthJournal
from ..util import paginate, get_current_group
from django.shortcuts import render


class JournalView(TemplateView):
    template_name = 'students/journal.html'

    def get_context_data(self, **kwargs):
        # get context data from TemplateView class
        context = super(JournalView, self).get_context_data(**kwargs)

        # check if we need to display some specific month
        if self.request.GET.get('month'):
            month = datetime.strptime(
                self.request.GET['month'], '%Y-%m-%d').date()
        else:
            # otherwise just displaying current month data
            today = datetime.today()
            month = date(today.year, today.month, 1)

        # calculate current, previous and next month details;
        # we need this for month navigation element in template
        next_month = month + relativedelta(months=1)
        prev_month = month - relativedelta(months=1)
        context['prev_month'] = prev_month.strftime('%Y-%m-%d')
        context['next_month'] = next_month.strftime('%Y-%m-%d')
        context['year'] = month.year
        context['month_verbose'] = month.strftime('%B')

        # we'll use this variable in students pagination
        context['cur_month'] = month.strftime('%Y-%m-%d')

        # prepare variable for template to generate
        # journal table header elements
        myear, mmonth = month.year, month.month
        number_of_days = monthrange(myear, mmonth)[1]
        context['month_header'] = [{'day': d,
                                    'verbose': day_abbr[weekday(myear, mmonth, d)][:3]}
                                   for d in range(1, number_of_days + 1)]

       # check if we need to show only one group of students
        current_group = get_current_group(self.request)
        if current_group:
            queryset = Student.objects.filter(
                student_group=current_group).order_by('last_name')
        elif kwargs.get('pk'):
            queryset = [Student.objects.get(pk=kwargs['pk'])]
        else:
            # otherwise show all students
            queryset = Student.objects.all().order_by('last_name')
            # queryset = []

        update_url = reverse('journal')

        # go over all students and collect data about presence
        # during selected month
        students = []
        for student in queryset:
            # try to get journal object by month selected
            # month and current student
            try:
                journal = MonthJournal.objects.get(student=student, date=month)
            except Exception:
                journal = None

            # fill in days presence list for current student
            days = []
            for day in range(1, number_of_days + 1):
                days.append({
                    'day': day,
                    'present': journal and getattr(journal, 'present_day%d' %
                                                   day, False) or False,
                    'date': date(myear, mmonth, day).strftime(
                        '%Y-%m-%d'),
                })

            students.append({
                'fullname': u'%s %s' % (student.last_name, student.first_name),
                'days': days,
                'id': student.id,
                'update_url': update_url,
            })

        # apply pagination, 10 students per page
        context = paginate(students, 5, self.request, context,
                           var_name='students')

        # finally return updated context
        # with paginated students
        return context

    def post(self, request, *args, **kwargs):
        # return JsonResponse({'key':'value'})
        data = request.POST

        # prepare student, dates and presence data
        current_date = datetime.strptime(data['date'], '%Y-%m-%d').date()
        month = date(current_date.year, current_date.month, 1)
        present = data['present'] and True or False
        student = Student.objects.get(pk=data['pk'])

        # get or create journal object for given student and month
        journal = MonthJournal.objects.get_or_create(student=student,
                                                     date=month)[0]

        # set new presence on journal for given student and save result
        setattr(journal, 'present_day%d' % current_date.day, present)
        journal.save()

        return JsonResponse({'status': 'success'})

students/views/logentries.py
# -*- coding: utf-8 -*-

from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.admin.models import LogEntry


def log_list(request):

    logs = LogEntry.objects.all()

    return render(request, 'students/log_list.html',
                  {'logs': logs})

students/templates/students/admin_change_group.html
{% extends "admin/base_site.html" %}

{% block content %}
  <form action="." method="post">
    {% csrf_token %}
    {{ form }}
    <input type="hidden" name="action" value="change_group" />
    <input  style="float: none" type="submit" name="do_action" value="Зберігти" />
    <p>Групу буде змінено у таких студентів:</p>
    <ul>
      {% for student in students %}
        <li>
          <a href="{{ student.pk }}/">{{ student }}</a> - {{ student.student_group }}
          <input type="hidden" name="_selected_action" value="{{ student.pk }}">
        </li>
      {% endfor %}
    </ul>
  </form>
{% endblock %}

students/templates/students/base.html
{% load i18n %}
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="uk"> 
  <head>
    <meta charset="UTF-8"/>
    <title>{% trans "Students Accounting Service" %} - {% block meta_title %}{% endblock meta_title %}</title> 
    <meta name="description" value="{% trans "App to manage students database" %}" />
    <!-- Dodaly styes -->

  <link rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" >
  <link rel="stylesheet" 
      href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.css">
  <link rel="stylesheet" href={{PORTAL_URL}}{% static "css/main.css" %}>


  <!-- 
      <script src="https://github.com/moment/moment/blob/develop/locale/ru.js"></script>
       <link rel="stylesheet" href="/static/css/main.css">
      <script type="" src={% static "js/ru.js" %}></script>
       -->

<!--     <style type="text/css">.col-xs-12, .col-xs-4, .col-xs-8, .col-xs-6,.col-xs-2,.col-xs-3, .col-xs-9 {border:1px solid red;}</style>-->
    
      {% block extra_css %}{% endblock extra_css %}
  </head>

  <body>
                    <!-- <h1>Вітаю вас на нашій сторінці!</h1> -->
                    <!-- <p>Поки тут порожньо, але незабаром ми матимемо список студентів</p> -->
      
      <!-- Start Container -->
      <div class="container">

        <!-- Start Header -->
        <div class="row" id="header">
         
          <!-- Logo -->
        
          <div class="col-xs-6"> 
<!--  {#          <h1>{% block logo %}Сервіс Обліку Студентів{% endblock logo %}</h1> #}-->
            <h1>{% trans "Students Accounting Service" %}</h1>
          </div>
          
<!--          <div id='loader'><img src="static/img/me.jpeg"/></div>-->
          
<!--    <img src="{{PORTAL_URL}}{% static "flags/Poland.png" %}" alt="..." class="img-responsive  ">

img src="{{PORTAL_URL}}{% static "flags/Poland.png" %}" alt="..." class="img-responsive"-->
            
            
<!--  {#          <h1>{% block logo %}Сервіс Обліку Студентів{% endblock logo %}</h1> #}-->
          
 <!--
          <div class="col-xs-3" id="languge-selector">

            <strong>{% trans "Language:" %}</strong>
              <select>
                {% for lang in LANGS %}
                  <option value="{{ lang.value }}"{% if lang.selected %}selected{% endif %} >
                    {{ lang.name }}  
                  </option>
                  <option value="uk" selected >Українська</option>
                  <option value="en" title="English" >English</option>
                  <option value="pl">Polski</option>
                {% endfor %}
              </select>

          </div>         
--> 
        <div class="col-xs-2" id="lang-flags">
<ul class="nav nav-tabs nav-justified">
            {% for lang in LANGUAGES %}
              <li>
                <form name="setLang{{ lang.1}}" action="/i18n/setlang/" method="POST">
                  {% csrf_token %}
                  <input type="hidden" name="next"  value="/">
                  <input type="hidden" name="language" value="{{ lang.0 }}">
                  <a href=""  onclick="document.setLang{{ lang.1 }}.submit();return false;">
                      <img id="img-lang" src=
                        {% ifequal lang.0 'pl'%} 
                          "{{PORTAL_URL}}{% static "flags/poland_glossy_square_icon_64.png" %}" title="Polski"  alt="Polski" class="img-responsive" 
                        {% endifequal %}

                        {% ifequal lang.0 'uk'%} 
                        "{{PORTAL_URL}}{% static "flags/ukraine_glossy_square_icon_64.png" %}" title="Ukrainian"  alt="Ukrainian" class="img-responsive"
                        {% endifequal %}

                        {% ifequal lang.0 'en'%} 
                          "{{PORTAL_URL}}{% static "flags/united_kingdom_glossy_square_icon_64.png" %}" title="English" alt="English" class="img-responsive"
                        {% endifequal %}

                    ></a>
                </form>
              </li>
            {% endfor %}   
          </ul>
        </div> 


    {% block selector %}

      {% if user.is_authenticated %}
<!-- Groups Selector -->
        <div class="col-xs-4" id="group-selector"> 
          <strong>{% trans "Group:" %}</strong>
            <select class="selectpicker">
              <option value="">{% trans "All Students" %}</option>
              {% for group in GROUPS %}
                <option value="{{ group.id }}"{% if group.selected %}selected="1"{% endif %}>
                   {{ group.title }} {% if group.starosta %}, {{ group.starosta }}{% endif %}
                </option>
              {% endfor %}
            </select>
        </div>

<!-- User's toolbar for authenticated users -->
        <div class="col-xs-4" id="user-toolbar"> 
        {# {% if user.first_name or user.last_name %} #}
          <a href="{% url "profile" %}">{{ user.get_full_name|default:user.username }} |</a>
   <!--       <span>{{ user.first_name }} {{ user.last_name }}</span> | -->

        {# {% else %} #}
   <!--        <span>{{ user.username }}</span> | -->
        {# {% endif %} #}
          <a href="{% url "users:auth_logout" %}">{% trans "Logout" %}</a>
        </div>

      {% else %}
<!-- User's toolbar for anonymous users -->
        <div class="col-xs-4" id="user-toolbar"> 
          <a href="{% url 'social:begin' 'facebook' %}?next= {{ request.path }} ">{% trans "via Facebook" %}</a> | 
        
          <a href="{% url "users:auth_login" %}">{% trans "Login" %}</a> | 
          <a href="{% url "users:registration_register" %}">{% trans "Register" %}</a>
        </div>
        
      {% endif %}

    {% endblock selector %}
  </div>
      <!-- End Header -->
      
<!--Тут оновили линкы головонои навигации:Студенти, Видвидування, групи, атрибуты "href"всередине 'a' тегов-->
<!--        {% block subheader %}{% endblock subheader %}-->

<!--Start subheader -->
        <div class="row" id="sub-header"> 
          <div class="col-xs-12">
            <ul class="nav nav-tabs " role="tablist">

             {% url 'home' as url1 %}
              <!--<li role="presentation" {% ifequal request.path url1 %}class="active"{% endifequal %}>-->
                  <!--<a href={% url "home" %}>Студенти</a></li>-->
              <!--<li role="presentation" {% if url1 == request.path  %}class="active"{% endif %}> rabotaet toje-->
              <!--<li role="presentation" {% if request.path = url1  %}class="active"{% endif %}>tak rabotaet toje. why?-->
<!--                 request.path += 'order_by=last_name'-->
<!--                 request.path = request.path|order_by=last_name-->

              <li role="presentation"
              {% if request.path == url1 %}
                class="active"
              {% endif %}>
                  <a class="glyphicon glyphicon-user" aria-hidden="true" href={% url "home" %}> <b>{% trans "Students" %}</b></a></li>
<!--                  <a href="{% url "home" %}?order_by=last_name">Студенти</a></li>-->
<!--                  <a href="{% url "home" %}?order_by=last_name{% if order_by == 'last_name' and reverse != '1' %}&amp;reverse=1{% endif %}">Студенти</a></li>                  -->
{% if user.is_authenticated %}

              {% url 'groups' as url3 %}
              <li role="presentation" {% ifequal request.path url3 %}class="active"{% endifequal %}>
                  <a class="glyphicon glyphicon-list" href={% url "groups" %}><b> {% trans "Groups" %}</b> </a></li>
              
               {% url 'exams' as url4 %}
              <li role="presentation" {% ifequal request.path url4 %}class="active"{% endifequal %}>
                  <a class="glyphicon glyphicon-education" href={% url "exams" %}> <b>{% trans "Exams" %}</b></a></li>
                  
              {% url 'journal' as url2 %}
              <li role="presentation" {% if url2 in request.path %}class="active"{% endif %}>
<!--              <li role="presentation" {% ifequal request.path url2 %}class="active"{% endifequal %}>-->
                  <a class="glyphicon glyphicon-calendar" href={% url "journal" %}>
                    <b>{% trans "Journal" %}</b>
                  </a>
              </li>
{% endif %}

{% if perms.auth.add_user %} 
              {% url 'log' as url6 %}
              <li role="presentation" {% ifequal request.path url6 %}class="active"{% endifequal %}>
            <a class="glyphicon glyphicon-transfer" href={% url "log" %}> <b>{% trans "Events" %}</b></a></li>

              {% url 'contact_admin' as url5 %}
              <li role="presentation" {% ifequal request.path url5 %}class="active"{% endifequal %}>
                  <a class="glyphicon glyphicon-envelope" href={% url "contact_admin" %}> <b>{% trans "Contact" %}</b></a></li>
{% endif %}    
            </ul>
          </div>
        </div>
<!-- End subheader -->
<!-- Start Main Page Content -->

         <!-- Start Content Columns -->
  <div class="row" id="content-columns">
    <div class="col-xs-12" id="content-column"> 
    <!-- Status Message -->
    {% block status_message %}
      {% if request.GET.status_message %}
          <div class="alert alert-success" role="alert"> {{request.GET.status_message}}
          </div>
      {% endif %}
    {% endblock %}
          <!-- End Content Columns -->

            <div class="col-xs-5" style="float: left;">
               <h2>{% block title %}{% endblock title %}</h2> 
            </div>
<!--
              <div class="col-xs-9" style="float: left;">
              </div>
-->{% block content %}      {% endblock content %}
      </div>
    </div>
  <!-- End Main Page Content --><!-- End Content Columns -->

           <!-- Start Footer -->
           {% block footer %}
          <div class="row" id="footer"> 
            <div class="col-xs-9">
              &copy;  {% trans "Students Accounting Service" %} - {% now "Y"%}
            </div>

            

              <div class="col-xs-3">
                  {% now "j E  | z | l H:i " %}
              </div>
<!--<div id="ajaxBusy"><p><img src="http://preloaders.net/images/ajax-loader.gif"></p></div>-->
<div id="ajaxBusy"><p><b>Йде збереження...</b></p></div>
<!--<div id="ajaxBusy"><p><img src="http://4.bp.blogspot.com/-R8AvkGGuNyk/Vg1un7XRePI/AAAAAAAAM1U/fw83vclJHeY/s1600/ajax-loader-2.gif"></p></div>-->
            <span id="ajax-progress-indicator"><b>Йде збереження...</b></span>
          </div>
          {% endblock footer %}
          <!-- End Footer -->

      <!-- END Container -->
      </div>

<!-- Modal window for groups -->    

<div class="modal fade" id="myModal1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Заголовок Редагувати групу </h4>
      </div>
      <div class="modal-body">
        <p>Тут будет форма редактирования группы&hellip;</p>
      </div>
      <div class="modal-footer"> <!-- --></div>

    </div><!-- /.modal-content --> 
  </div> <!-- /.modal-dialog --> 
</div><!-- .modal  --> 
    

    
    
    
<!-- Modal Boilerplate -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog"
       aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"
                  aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel"><!-- --></h4>
        </div>
        <div class="modal-body"><!-- --></div>
        <div class="modal-footer"> <!-- --></div>
      </div>
    </div>
  </div>



      <!-- Javascripts Section --> <!-- Javascripts Inclusion -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>      
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/3.51/jquery.form.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js"></script>
      <script type="" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/locale/uk.js"></script>
<!--      <script src="{% static "js/jquery.cookie.js" %}"></script>-->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>      
      <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>
      <script src="{% url "django.views.i18n.javascript_catalog" %}"></script>
      <script type="" src={% static "js/main.js" %}></script>
    {% block extra_js %}
    {% endblock extra_js %}

  </body>
</html>